-- This file has inserts for all known nutrients from the FDC API
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Energy', 'kcal', 300, 1008);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Protein', 'g', 600, 1003);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Total lipid (fat)', 'g', 800, 1004);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Carbohydrate, by difference', 'g', 1110, 1005);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Alcohol, ethyl', 'g', 18200, 1018);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Water', 'g', 100, 1051);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Caffeine', 'mg', 18300, 1057);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Theobromine', 'mg', 18400, 1058);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Sugars, total including NLEA', 'g', 1510, 2000);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Fiber, total dietary', 'g', 1200, 1079);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Calcium, Ca', 'mg', 5300, 1087);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Iron, Fe', 'mg', 5400, 1089);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Magnesium, Mg', 'mg', 5500, 1090);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Phosphorus, P', 'mg', 5600, 1091);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Potassium, K', 'mg', 5700, 1092);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Sodium, Na', 'mg', 5800, 1093);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Zinc, Zn', 'mg', 5900, 1095);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Copper, Cu', 'mg', 6000, 1098);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Selenium, Se', 'µg', 6200, 1103);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Retinol', 'µg', 7430, 1105);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin A, RAE', 'µg', 7420, 1106);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Carotene, beta', 'µg', 7440, 1107);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Carotene, alpha', 'µg', 7450, 1108);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin E (alpha-tocopherol)', 'mg', 7905, 1109);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin D (D2 + D3)', 'µg', 8700, 1114);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Cryptoxanthin, beta', 'µg', 7460, 1120);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Lycopene', 'µg', 7530, 1122);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Lutein + zeaxanthin', 'µg', 7560, 1123);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin C, total ascorbic acid', 'mg', 6300, 1162);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Thiamin', 'mg', 6400, 1165);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Riboflavin', 'mg', 6500, 1166);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Niacin', 'mg', 6600, 1167);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin B-6', 'mg', 6800, 1175);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Folate, total', 'µg', 6900, 1177);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin B-12', 'µg', 7300, 1178);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Choline, total', 'mg', 7220, 1180);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin K (phylloquinone)', 'µg', 8800, 1185);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Folic acid', 'µg', 7000, 1186);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Folate, food', 'µg', 7100, 1187);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Folate, DFE', 'µg', 7200, 1190);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin E, added', 'mg', 7920, 1242);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin B-12, added', 'µg', 7340, 1246);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Cholesterol', 'mg', 15700, 1253);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Fatty acids, total saturated', 'g', 9700, 1258);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('4:0', 'g', 9800, 1259);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('6:0', 'g', 9900, 1260);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('8:0', 'g', 10000, 1261);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('10:0', 'g', 10100, 1262);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('12:0', 'g', 10300, 1263);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('14:0', 'g', 10500, 1264);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('16:0', 'g', 10700, 1265);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('18:0', 'g', 10900, 1266);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('18:1', 'g', 12100, 1268);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('18:2', 'g', 13100, 1269);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('18:3', 'g', 13900, 1270);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('20:4', 'g', 14700, 1271);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('22:6 n-3 (DHA)', 'g', 15300, 1272);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('16:1', 'g', 11700, 1275);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('18:4', 'g', 14250, 1276);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('20:1', 'g', 12400, 1277);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('20:5 n-3 (EPA)', 'g', 15000, 1278);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('22:1', 'g', 12500, 1279);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('22:5 n-3 (DPA)', 'g', 15200, 1280);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Fatty acids, total monounsaturated', 'g', 11400, 1292);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Fatty acids, total polyunsaturated', 'g', 12900, 1293);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin A, IU', 'IU', 7500, 1104);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Fatty acids, total trans', 'g', 15400, 1257);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Proximates', 'g', 50, 2045);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamin D (D2 + D3), International Units', 'IU', 8650, 1110);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Energy', 'kJ', 400, 1062);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Ash', 'g', 1000, 1007);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Carbohydrates', 'g', 1100, 2039);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Minerals', 'mg', 5200, 2043);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Manganese, Mn', 'mg', 6100, 1101);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Vitamins and Other Components', 'g', 6250, 2046);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Pantothenic acid', 'mg', 6700, 1170);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Lipids', 'g', 9600, 2044);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Amino acids', 'g', 16250, 2042);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Tryptophan', 'g', 16300, 1210);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Threonine', 'g', 16400, 1211);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Isoleucine', 'g', 16500, 1212);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Leucine', 'g', 16600, 1213);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Lysine', 'g', 16700, 1214);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Methionine', 'g', 16800, 1215);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Cystine', 'g', 16900, 1216);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Phenylalanine', 'g', 17000, 1217);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Tyrosine', 'g', 17100, 1218);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Valine', 'g', 17200, 1219);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Arginine', 'g', 17300, 1220);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Histidine', 'g', 17400, 1221);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Alanine', 'g', 17500, 1222);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Aspartic acid', 'g', 17600, 1223);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Glutamic acid', 'g', 17700, 1224);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Glycine', 'g', 17800, 1225);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Proline', 'g', 17900, 1226);
INSERT INTO nutrients (nutrient_name, unit_name, rank, fdc_id) VALUES ('Serine', 'g', 18000, 1227);
